repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.17
    hooks:
      # Dependency management
      - id: uv-lock
        name: uv-lock (Update uv.lock if pyproject.toml changed)
        files: ^pyproject\.toml$

    # Code quality and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: debug-statements

    # Python Linting & Formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        name: ruff (linter)
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format
        name: ruff-format (formatter)

    # Type checking with MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        args: ["--config-file", "pyproject.toml"]
        files: ^(src/|tests/)
        additional_dependencies:
          - types-boto3
          - typer
          - pytest

    # No committing secrets
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
