name: CI

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  test:
    name: Setup and Run Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project and dependencies
        run: |
          uv sync --all-extras --dev
          uv pip install -e . --no-deps

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create dummy .env file
        run: |
          echo "R2_ACCOUNT_ID=dummy-id" >> .env
          echo "R2_ACCESS_KEY_ID=dummy-key" >> .env
          echo "R2_SECRET_ACCESS_KEY=dummy-secret" >> .env
          echo "R2_BUCKET=dummy-bucket" >> .env

      - name: Run tests
        run: uv run pytest tests
